# Generated by Django 4.2.13 on 2024-08-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
    ]
